# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b
  
checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  checkpoint_dir: /opt/ml/input/data/model/model_artifacts
  checkpoint_files: [
    consolidated.00.pth
  ]
  output_dir:  /opt/ml/model/hf-output
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /opt/ml/input/data/model/model_artifacts/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: '{"dialogue":"Amanda: I baked  cookies. Do you want some?\nJerry: Sure \nAmanda: I will bring you tomorrow :-)"}'
#instruct_template: torchtune.data.SummarizeTemplate

#chat_format: null
max_new_tokens: 30
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
enable_kv_cache: False

quantizer: null
instruct_template: CustomTemplate.SummarizeTemplate

#instruct_template: CustomTemplate.SummarizeTemplate
